pipeline {
    agent any
    environment {
        PATH = "$PATH:/usr/local/bin"
    }
    stages {
        stage('Build') { 
            steps {
                sh "npm install"
            }
        }
        stage('Test') { 
            steps {
                sh "npm install && npm test"
            }
        }
        stage('Image Build') { 
            steps {
                sh "docker build -t fibo:1 ."
            }
        }
        stage('Helm Deploy') { 
            steps {
                sh "pwd; ls -l; cd helm && helm upgrade -i fibo fibo -f fibo/values.yaml -f fibo/values/local.yaml"
            }
        }
    }
}